### ISSUE TITLE
感想

### ISSUE THREAD

**Issue by Aki-7** [liwii/CodablePPTX#1]
なんとなくおもったことで、そこまで深く考えてないけど

多分、GUIアプリケーションを立ち上げるより、コーディングでPPTがかけたら楽っていうモチベーションだと思うんだけど、

本当に簡単なスライドを用意すればいい時には楽でいいと思った。

でもある程度レイアウト凝りたくなったら、使ってるpython ライブラリをそのまま使った方が楽そう。

こんなフォーマットの方が覚えやすそうだし、いろんなことができそう
```yaml
slides:
  - text:
    - value: "Title"
    - position: "left"
    - fontSize: 20
    img:
    - value: "sample.png"
    - position: "right"
 - img:
    - value: "sample2.png"
    - position: "center"
    - size: "300x"
    text:
    - value: "from xxx.com"
    - position:
      - top: "90%"
      - left: "70%"
    - fontSize: 8
```

もしくはhtmlとcssまたはmarkdownでかけたら嬉しいかも
